import {
    compareBlockFactory,
    correctBlockFactory,
    declarationFactory,
    highBlockFactory,
    ifBlockFactory,
    inputBlockFactory,
    lessThanBlockFactory,
    lowBlockFactory,
    multiplyBlockFactory,
    printStingBlockFactory,
    randBlockFactory,
    startSignalFactory,
    tenBlockFactory,
    trueBlockFactory,
    whileBlockFactory
} from "./factories/factories";

export const activeBlocks = [
    startSignalFactory,
    declarationFactory,
    ifBlockFactory,
    whileBlockFactory,
    trueBlockFactory,
    compareBlockFactory,
    lessThanBlockFactory,
    inputBlockFactory,
    randBlockFactory,
    tenBlockFactory,
    multiplyBlockFactory,
    correctBlockFactory,
    highBlockFactory,
    lowBlockFactory,
    printStingBlockFactory,
];